<a href="https://colab.research.google.com/github/Nandinikhandade/MachineLearning/blob/main/Loan_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from numpy import random
import os
os.getcwd()
os.chdir("/content/drive/MyDrive")
os.getcwd
import statsmodels.api as sm
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_excel("loan_logistic_regression_dataset.xlsx")
df.head()

   Age  Monthly_Income  Credit_Score Gender Education_Level  Loan_Approved
0   26           37958           406   Male             PhD              0
1   47           34272           797   Male        Bachelor              1
2   25           28351           649   Male          Master              0
3   41           74724           786   Male          Master              1
4   45           51021           534   Male        Bachelor              0

In [3]:
df = pd.get_dummies(df,columns=["Gender","Education_Level"],drop_first=True).astype(int)

In [4]:
df.head()

,Age,Monthly_Income,Credit_Score,Loan_Approved,Gender_Male,Education_Level_High School,Education_Level_Master,Education_Level_PhD
0,26,37958,406,0,1,0,0,1
1,47,34272,797,1,1,0,0,0
2,25,28351,649,0,1,0,1,0
3,41,74724,786,1,1,0,1,0
4,45,51021,534,0,1,0,0,0

In [5]:
x = df.drop("Loan_Approved", axis=1)

y = df["Loan_Approved"]

In [6]:

x_train, x_test, y_train, y_test = train_test_split( x, y,test_size=0.20,random_state=20)

In [7]:
x_train=sm.add_constant(x_train,prepend=False)
x_test=sm.add_constant(x_test,prepend=False)

In [8]:

x_train.head()

,Age,Monthly_Income,Credit_Score,Gender_Male,Education_Level_High School,Education_Level_Master,Education_Level_PhD,const
40,51,70192,569,1,0,1,0,1.0
17,29,60520,769,1,0,0,0,1.0
18,22,86726,385,0,0,0,0,1.0
0,26,37958,406,1,0,0,1,1.0
27,36,75741,335,1,0,1,0,1.0

In [9]:
x_train.shape

(40, 8)

In [10]:

x_test.shape

(10, 8)

In [13]:
model = sm.Logit(y_train, x_train)
# result = model.fit(method="bfgs", maxiter=500)
result = model.fit_regularized(method='l1', alpha = 0.1)

print(result.summary())

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.11355637258222046
            Iterations: 99
            Function evaluations: 114
            Gradient evaluations: 99
                           Logit Regression Results
==============================================================================
Dep. Variable:          Loan_Approved   No. Observations:                   40
Model:                          Logit   Df Residuals:                       32
Method:                           MLE   Df Model:                            7
Date:                Sat, 27 Jun 2026   Pseudo R-squ.:                  0.9469
Time:                        05:59:00   Log-Likelihood:                -1.4721
converged:                       True   LL-Null:                       -27.726
Covariance Type:            nonrobust   LLR p-value:                 4.637e-09
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Age                             0.1504      0.110      1.367      0.172      -0.065       0.366
Monthly_Income                  0.0001   4.92e-05      2.065      0.039    5.18e-06       0.000
Credit_Score                    0.0282      0.012      2.395      0.017       0.005       0.051
Gender_Male                    -0.2941      2.164     -0.136      0.892      -4.536       3.947
Education_Level_High School    -1.7504      3.295     -0.531      0.595      -8.208       4.708
Education_Level_Master          0.0643      2.963      0.022      0.983      -5.744       5.872
Education_Level_PhD             0.0546      3.457      0.016      0.987      -6.721       6.830
const                         -28.3591     10.420     -2.722      0.006     -48.782      -7.936
===============================================================================================

/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
/usr/local/lib/python3.12/dist-packages/statsmodels/base/l1_solvers_common.py:71: ConvergenceWarning: QC check did not pass for 1 out of 8 parameters
Try increasing solver accuracy or number of iterations, decreasing alpha, or switch solvers
  warnings.warn(message, ConvergenceWarning)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/l1_solvers_common.py:144: ConvergenceWarning: Could not trim params automatically due to failed QC check. Trimming using trim_mode == 'size' will still work.
  warnings.warn(msg, ConvergenceWarning)

In [ ]:

# 1. H0 = age does not influence target
# 2. checking p value if p value more than level of significance
# 3. we do not reject the null hypothesis.
# 4. it means age does not influence the target
# 5. for every unit increase in age the log of odds ratio in favor of getting Loan_Approved change by 0.1504