In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [190]:
df = pd.read_excel('/Users/nandini/Downloads/SalesData (2).xlsx')

In [172]:
df.head()

   Advertising  Temperature  Gender Region   Sales
0        57.45        25.82  Female   West  433.23
1        47.93        38.39    Male  South  386.91
2        59.72        24.37    Male   West  518.70
3        72.85        18.73    Male   West  466.22
4        46.49        17.55  Female  North  345.77

In [173]:
df = pd.get_dummies(df,columns=['Gender','Region'],drop_first=True).astype(int)

In [174]:
x.head()

,Advertising,Temperature,Gender_Male,Region_North,Region_South,Region_West
0,57,25,0,0,0,1
1,47,38,1,0,1,0
2,59,24,1,0,0,1
3,72,18,1,0,0,1
4,46,17,0,1,0,0

In [175]:
x = df.drop('Sales', axis=1)
y = df['Sales']

In [176]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=20)

In [177]:
x_train.head()

,Advertising,Temperature,Gender_Male,Region_North,Region_South,Region_West
346,28,35,0,1,0,0
91,64,31,1,0,1,0
299,59,34,1,0,0,1
129,42,27,0,0,0,0
695,45,31,0,0,1,0

In [ ]:
x_train = sm.add_constant(x_train,prepend=False)

In [179]:
x_train.head()

,Advertising,Temperature,Gender_Male,Region_North,Region_South,Region_West,const
346,28,35,0,1,0,0,1.0
91,64,31,1,0,1,0,1.0
299,59,34,1,0,0,1,1.0
129,42,27,0,0,0,0,1.0
695,45,31,0,0,1,0,1.0

In [180]:
mod1 = sm.OLS(y_train, x_train).fit()

In [181]:
print(mod1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.802
Model:                            OLS   Adj. R-squared:                  0.800
Method:                 Least Squares   F-statistic:                     373.0
Date:                Tue, 23 Jun 2026   Prob (F-statistic):          1.01e-190
Time:                        20:47:56   Log-Likelihood:                -2789.6
No. Observations:                 560   AIC:                             5593.
Df Residuals:                     553   BIC:                             5624.
Df Model:                           6
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Advertising      4.6753      0.101     46.257      0.000       4.477       4.874
Temperature      0.2747      0.191      1.436      0.152      -0.101       0.651
Gender_Male     12.8748      3.027      4.254      0.000       6.929      18.820
Region_North   -18.6376      4.289     -4.346      0.000     -27.062     -10.214
Region_South    -4.6478      4.533     -1.025      0.306     -13.552       4.256
Region_West     23.4241      4.533      5.167      0.000      14.519      32.329
const          126.2625      8.599     14.684      0.000     109.372     143.153
==============================================================================
Omnibus:                        0.252   Durbin-Watson:                   2.035
Prob(Omnibus):                  0.882   Jarque-Bera (JB):                0.131
Skew:                          -0.011   Prob(JB):                        0.937
Kurtosis:                       3.072   Cond. No.                         364.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
# H0 = Advertising does not influence sales
# checking p values if p value less than level of significance
# we reject the null hypothesis
# it means advertising does influence the sales
# for every unit increase in advertising the the sales will increase by 4.6753

In [ ]:
# H0 = temperature does not influence sales
# checking p values if p value more than level of significance
# we do not reject the null hypothesis
# it means temperature does not influence the sales

In [ ]:
# h0= with respect to female if a male is selected that it does not influence the sales
# checking p value if p value less than level of significance
# we reject the null hypothesis
# it means with respect to female if a male is selcted that it does influence the sales
# with respect to female if you choose male then it will driectly increase the coef of sales by 12.8748

In [ ]:
# h0= with respect to east if region north is selected that it does not influence the sales
# checking p value if p value less than level of significance
# we reject the null hypothesis
# it means with respect to east if a region north is selcted that it does influence the sales
# with respect to east if you choose north then it will driectly decrease the coef of sales by -18.6376

In [ ]:
# h0= with respect to east if a region south is selected that it does not influence the sales
# checking p value if p value more than level of significance
# we do not reject the null hypothesis
# it means with respect to east if a south is selcted that it does not influence the sales
# with respect to east if you choose south region then it will driectly decrease the coef of sales by -4.6478

In [ ]:
# h0= with respect to east if region west is selected that it does not influence the sales
# checking p value if p value less than level of significance
# we reject the null hypothesis
# it means with respect to east if a region west is selcted that it does influence the sales
# with respect to east if you choose west then it will driectly increase the coef of sales by 23.4241